name: Upload Python Package to Azure Artifacts 

on:
  push:
    tags:
      - '*'
env:
  POETRY_VERSION: 2.1.1

permissions: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipx
      - run: |
          python -m pip install pipx
          pipx ensurepath

      - name: Install Poetry
        run: |
          pipx install poetry=${{ env.POETRY_VERSION }}

      - name: Configure Poetry for Azure DevOps
        run: |
          poetry config repositories.azure "https://pkgs.dev.azure.com/Axpo-AXSO/POC-SET/_packaging/QuantFabricFeed/pypi/upload"
          export POETRY_PYPI_TOKEN_AZURE=${{ secrets.AZURE_ARTIFACTS_RW_TOKEN }}

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Build Package
        run: poetry build

      - name: Publish Package to Azure DevOps
        run: poetry publish -r azure --build
        
